name: Push dataset to Kaggle

on:
  push:
    branches: [main]
    paths:
      - 'dataset/**'
      - 'dataset-metadata.json'
      - 'metadata.json'

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Kaggle CLI
        run: pip install kaggle

      - name: Masking credentials
        run: echo "::add-mask::${{ secrets.KAGGLE_KEY }}"

      - name: Set dataset-metadata.json
        run: base64 -d <<< "${{ secrets.DATASET_METADATA }}" > dataset-metadata.json

      - name: Upload dataset
        env:
          KAGGLE_USERNAME:        pholenk
          KAGGLE_KEY:             ${{ secrets.KAGGLE_KEY }}
          KAGGLE_API_TOKEN:       ${{ secrets.KAGGLE_KEY }}
        run: |
          kaggle datasets version \
            -m "Update: ${{ github.event.head_commit.message }}" \
            --dir-mode zip
